version: '3.9'

services:
  mmdvm_host:
    build: ./MMDVMHost
    restart: always
    volumes:
      - mmdvmhost:/MMDVMHost
    devices:
      - dev/ttyAMA0:/dev/ttyAMA0
  analog_bridge:
    build: ./AnalogBridge
    restart: always
    ports:
      - 34001:34001
      - 32001:32001
  hblink:
    build: ./HBLink
    restart: always

volumes:
  mmdvmhost:
